language: python
before_install:
- sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
- sudo apt-get update -qq
install:
- sudo apt-get install -y freecad
- gcc --version
- g++ --version
- python ./setup.py install
- pip install -r requirements-dev.txt
- pip install travis-sphinx
- pip install sphinx_rtd_theme

script:
- coverage run --source=cadquery ./runtests.py
- travis-sphinx build --nowarn --source=doc

after_success:
- coveralls
- travis-sphinx deploy

branches:
  except:
  - pythonocc
  - 2_0_branch

  deploy:
  provider: pypi
  user: dcowden
  password:
    secure: aP02wBbry1j3hYG/w++siF1lk26teuRQlPAx1c+ec8fxUw+bECa2HbPQHcIvSXB5N6nc6P3L9LjHt9ktm+Dn6FLJu3qWYNGAZx9PTn24ug0iAmB+JyNrsET3nK6WUKR1XpBqvjKgdpukd1Hknh2FSzYoyUvFWH9/CovITCFN3jo=
  on:
    tags: true