language: python
before_install:
- sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
- sudo apt-get update -qq
install:
- sudo apt-get install 
- sudo apt-get install -y wget bzip2 freecad freecad-doc
- sudo wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
- sudo bash Miniconda2-latest-Linux-x86_64.sh -b -p /opt/conda
- sudo export PATH=$PATH:/opt/conda/bin
- sudo conda install -y -c pythonocc -c dlr-sc pythonocc-core==0.17.1 python=2
- pip install -r requirements-dev.txt
- python ./setup.py install
script:
#weird. we actually have two coverages-- one with each backend. not sure which to report.
#the last one wins here.
- CQ_BACKEND=FreeCAD && py.test -s --cov
- CQ_BACKEND=pythonOCC && py.test -s --cov
after_success:
- coveralls
#- travis-sphinx deploy
branches:
  except:
  - pythonocc
#deploy:
#  provider: pypi
#  user: dcowden
#  password:
#    secure: aP02wBbry1j3hYG/w++siF1lk26teuRQlPAx1c+ec8fxUw+bECa2HbPQHcIvSXB5N6nc6P3L9LjHt9ktm+Dn6FLJu3qWYNGAZx9PTn24ug0iAmB+JyNrsET3nK6WUKR1XpBqvjKgdpukd1Hknh2FSzYoyUvFWH9/CovITCFN3jo=
#  on:
#    tags: true
